# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sonny Hu 
tagline:             'Blog'
url:                 http://sonnyhu.github.io/sonnyhu.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             1.0.0
github:
  repo:              github.com/sonnyhu/sonnyhu.github.io

pages_list: {
  'About': '/about',
  'Archive': '/archive',
  'Feed': '/atom.xml'
}